# Compiler and linker settings
CXX := g++
LD := g++

# Directories
SRC_DIR := src
OBJ_DIR := obj
BIN_DIR := bin

# Source files
SRCS := $(wildcard $(SRC_DIR)/*.cpp)
OBJS := $(patsubst $(SRC_DIR)/%.cpp, $(OBJ_DIR)/%.o, $(SRCS))

# Compiler and linker flags
CXXFLAGS := -std=c++11 -Wall -Wextra -Iinclude
LDFLAGS := -lsfml-graphics -lsfml-window -lsfml-system

# Output binary
EXECUTABLE := $(BIN_DIR)/pong

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	@mkdir -p $(BIN_DIR)
	$(LD) $(OBJS) $(LDFLAGS) -o $@

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@mkdir -p $(OBJ_DIR)
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	$(RM) -r $(OBJ_DIR) $(BIN_DIR)

.PHONY: all clean
